# Generated by Django 5.2 on 2025-05-25 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de fin')),
                ('dias_permitidos', models.CharField(help_text='Selecciona los días permitidos separados por coma (ej: lunes,martes,viernes)', max_length=100, verbose_name='Días permitidos')),
                ('activa', models.BooleanField(default=True, verbose_name='Configuración activa')),
            ],
        ),
    ]
