# Generated by Django 5.2 on 2025-06-15 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('fecha_fin', models.DateField()),
                ('hora_fin', models.TimeField()),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
    ]
