# Generated by Django 5.2 on 2025-05-31 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionregistro',
            name='registro_habilitado',
            field=models.BooleanField(default=False),
        ),
    ]
