# Generated by Django 5.2 on 2025-06-15 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracionregistro',
            options={'verbose_name': 'Configuración de Registro', 'verbose_name_plural': 'Configuraciones de Registro'},
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('action', models.CharField(help_text="Ej. 'user_created', 'role_assigned', 'solicitud_aprobada'", max_length=100, verbose_name='Tipo de Acción')),
                ('object_repr', models.CharField(blank=True, help_text="Representación textual del objeto (ej. 'Aula Laboratorio 3', 'Usuario juan.perez')", max_length=255, verbose_name='Objeto Afectado')),
                ('change_message', models.TextField(blank=True, help_text='Mensaje descriptivo del cambio realizado', verbose_name='Detalle del Cambio')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='administrador_log_entries', to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, help_text='Usuario que realizó el cambio', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Cambio',
                'verbose_name_plural': 'Registros de Cambios',
                'ordering': ['-action_time'],
            },
        ),
    ]
