# Generated by Django 5.2 on 2025-06-05 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0002_configuracionregistro_registro_habilitado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracionregistro',
            name='dias_permitidos',
        ),
        migrations.RemoveField(
            model_name='configuracionregistro',
            name='registro_habilitado',
        ),
        migrations.AddField(
            model_name='configuracionregistro',
            name='fecha_fin',
            field=models.DateField(default='2025-06-04'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configuracionregistro',
            name='fecha_inicio',
            field=models.DateField(default='2025-06-04'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='configuracionregistro',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='configuracionregistro',
            name='hora_fin',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='configuracionregistro',
            name='hora_inicio',
            field=models.TimeField(),
        ),
    ]
