# Generated by Django 5.2 on 2025-05-19 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='SolicitudUsuario',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
