# Generated by Django 5.2 on 2025-06-15 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitudusuario',
            options={'ordering': ['-fecha_solicitud'], 'verbose_name': 'Solicitud de Usuario', 'verbose_name_plural': 'Solicitudes de Usuarios'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AddField(
            model_name='solicitudusuario',
            name='fecha_revision',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudusuario',
            name='revisado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_revisadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solicitudusuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('coordinador', 'Coordinador'), ('profesor', 'Profesor'), ('operativo', 'Operativo'), ('super_admin', 'Super Administrador')], default='profesor', max_length=20, verbose_name='Rol general'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cargo_departamental',
            field=models.CharField(blank=True, choices=[('programacion', 'Jefe de Programación Académica'), ('servicio_social', 'Jefe de Servicio Social'), ('trabajo_grado', 'Jefe de Trabajo de Grado'), ('investigacion', 'Jefe de Investigación'), ('extension', 'Jefe de Extensión'), ('ninguno', 'Ninguno')], default='ninguno', max_length=30, null=True, verbose_name='Cargo Departamental'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('coordinador', 'Coordinador'), ('profesor', 'Profesor'), ('operativo', 'Operativo'), ('super_admin', 'Super Administrador')], default='profesor', max_length=20, verbose_name='Rol general'),
        ),
    ]
