# Generated by Django 5.2 on 2025-05-23 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudusuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('coordinador', 'Coordinador'), ('profesor', 'Profesor'), ('operativo', 'Operativo')], default='profesor', max_length=20, verbose_name='Rol general'),
        ),
    ]
