# Generated by Django 5.2 on 2025-06-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudusuario',
            name='username',
        ),
        migrations.AddField(
            model_name='solicitudusuario',
            name='cedula',
            field=models.CharField(default='default_cedula', max_length=20, unique=True, verbose_name='Cédula'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitudusuario',
            name='telefono_movil',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono Móvil'),
        ),
    ]
