# Generated by Django 5.2 on 2025-06-15 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_solicitudusuario_options_alter_usuario_options_and_more'),
        ('programacion', '0003_departamento_facultad_alter_carrera_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Cargo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción del Cargo')),
                ('es_jefatura', models.BooleanField(default=False, verbose_name='¿Es un cargo de Jefatura/Dirección?')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'ordering': ['nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='cargo_departamental',
        ),
        migrations.AddField(
            model_name='usuario',
            name='carrera_asignada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directores_coordinadores', to='programacion.carrera', verbose_name='Carrera Asignada (si aplica)'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='departamento_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jefes_coordinadores', to='programacion.departamento', verbose_name='Departamento Asignado (si aplica)'),
        ),
        migrations.AlterField(
            model_name='solicitudusuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('coordinador', 'Coordinador'), ('profesor', 'Profesor'), ('operativo', 'Operativo'), ('super_admin', 'Super Administrador')], default='profesor', max_length=20, verbose_name='Rol general sugerido'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('coordinador', 'Coordinador'), ('profesor', 'Profesor'), ('operativo', 'Operativo'), ('super_admin', 'Super Administrador')], default='profesor', max_length=20, verbose_name='Rol del Sistema'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_con_este_cargo', to='accounts.cargo', verbose_name='Tipo de Cargo'),
        ),
    ]
