# Generated by Django 5.2 on 2025-06-16 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_cargo_remove_usuario_cargo_departamental_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='permissions',
            field=models.JSONField(blank=True, default=dict, help_text='Permisos granulares asociados a este cargo (formato JSON).', null=True),
        ),
    ]
