# Generated by Django 5.2 on 2025-06-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usuario_cedula'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='telefono_movil',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono Móvil'),
        ),
    ]
