# Generated by Django 5.2 on 2025-06-10 06:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio_social', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviciosocial',
            name='estudiante',
        ),
        migrations.AddField(
            model_name='serviciosocial',
            name='estudiantes',
            field=models.ManyToManyField(blank=True, related_name='servicios_sociales_participados', to=settings.AUTH_USER_MODEL),
        ),
    ]
