# Generated by Django 5.2 on 2025-06-24 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacion', '0008_alter_asignatura_semestre'),
        ('servicio_social', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviciosocial',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='serviciosocial',
            name='fecha_inicio',
        ),
        migrations.AddField(
            model_name='serviciosocial',
            name='periodo_academico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='programacion.periodo', verbose_name='Período Académico'),
            preserve_default=False,
        ),
    ]
