# Generated by Django 5.2 on 2025-06-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio_social', '0002_remove_serviciosocial_estudiante_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviciosocial',
            name='estudiantes',
        ),
        migrations.AddField(
            model_name='serviciosocial',
            name='nombres_estudiantes_manual',
            field=models.TextField(blank=True, help_text='Introduce los nombres completos de los estudiantes, separados por comas o saltos de línea.', null=True, verbose_name='Nombres de Estudiantes (Manual)'),
        ),
    ]
