# Generated by Django 5.2 on 2025-06-11 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacion', '0011_alter_asignatura_semestre_alter_horarioaula_semestre_and_more'),
        ('servicio_social', '0003_remove_serviciosocial_estudiantes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviciosocial',
            options={'verbose_name': 'Servicio Social', 'verbose_name_plural': 'Servicios Sociales'},
        ),
        migrations.RemoveField(
            model_name='serviciosocial',
            name='cedula_tutor',
        ),
        migrations.RemoveField(
            model_name='serviciosocial',
            name='nombres_estudiantes_manual',
        ),
        migrations.RemoveField(
            model_name='serviciosocial',
            name='tutor',
        ),
        migrations.AddField(
            model_name='serviciosocial',
            name='act_alianzas_estrategicas',
            field=models.BooleanField(default=False, verbose_name='Alianzas Estratégicas Realizadas'),
        ),
        migrations.AddField(
            model_name='serviciosocial',
            name='act_campanas',
            field=models.BooleanField(default=False, verbose_name='Campañas Realizadas'),
        ),
        migrations.AddField(
            model_name='serviciosocial',
            name='act_charlas',
            field=models.BooleanField(default=False, verbose_name='Charlas Realizadas'),
        ),
        migrations.AddField(
            model_name='serviciosocial',
            name='act_ferias',
            field=models.BooleanField(default=False, verbose_name='Ferias Realizadas'),
        ),
        migrations.AddField(
            model_name='serviciosocial',
            name='act_foros',
            field=models.BooleanField(default=False, verbose_name='Foros Realizados'),
        ),
        migrations.AddField(
            model_name='serviciosocial',
            name='act_jornadas',
            field=models.BooleanField(default=False, verbose_name='Jornadas Realizadas'),
        ),
        migrations.AddField(
            model_name='serviciosocial',
            name='act_reunion_misiones',
            field=models.BooleanField(default=False, verbose_name='Reuniones con Misiones Realizadas'),
        ),
        migrations.AddField(
            model_name='serviciosocial',
            name='act_talleres',
            field=models.BooleanField(default=False, verbose_name='Talleres Realizados'),
        ),
        migrations.AddField(
            model_name='serviciosocial',
            name='area_accion_proyecto',
            field=models.CharField(choices=[('ambiental', 'Ambiental'), ('socioproductivo', 'Socioproductivo'), ('tecnologico', 'Tecnológico'), ('social', 'Social'), ('educativo', 'Educativo'), ('socio_comunitario', 'Socio-Comunitario'), ('otros', 'Otros')], default='otro', help_text='Selecciona el área principal de acción del proyecto.', max_length=50, verbose_name='Área de Acción del Proyecto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviciosocial',
            name='cantidad_beneficiados',
            field=models.PositiveIntegerField(default=0, help_text='Solo números.', verbose_name='Cantidad de Beneficiados'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviciosocial',
            name='direccion_comunidad',
            field=models.TextField(default='', verbose_name='Dirección de la Comunidad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviciosocial',
            name='nombre_comunidad_institucion',
            field=models.CharField(default='', max_length=255, verbose_name='Nombre de la Comunidad y/o Institución'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviciosocial',
            name='tutor_apellidos',
            field=models.CharField(default='', max_length=100, verbose_name='Apellidos del Tutor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviciosocial',
            name='tutor_categoria_docente',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Categoría Docente (si es Docente)'),
        ),
        migrations.AddField(
            model_name='serviciosocial',
            name='tutor_cedula',
            field=models.CharField(default='', max_length=15, verbose_name='Cédula de Identidad del Tutor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviciosocial',
            name='tutor_comunitario_cedula',
            field=models.CharField(default='', max_length=15, verbose_name='Cédula de Identidad del Tutor Comunitario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviciosocial',
            name='tutor_comunitario_nombre',
            field=models.CharField(default='', max_length=100, verbose_name='Nombre del Tutor Comunitario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviciosocial',
            name='tutor_comunitario_telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono del Tutor Comunitario'),
        ),
        migrations.AddField(
            model_name='serviciosocial',
            name='tutor_nombres',
            field=models.CharField(default='', max_length=100, verbose_name='Nombres del Tutor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviciosocial',
            name='tutor_tipo',
            field=models.CharField(choices=[('administrativo', 'Administrativo'), ('docente', 'Docente')], default='', max_length=20, verbose_name='Tipo de Tutor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviciosocial',
            name='tutor_unidad_administrativa',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Unidad Administrativa (si es Administrativo)'),
        ),
        migrations.AddField(
            model_name='serviciosocial',
            name='vinculacion_planes_programas',
            field=models.TextField(default='', verbose_name='Vinculación del Proyecto con Planes, Programas y/o Proyectos del Ejecutivo Nacional'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serviciosocial',
            name='departamento',
            field=models.CharField(max_length=100, verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='serviciosocial',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('finalizado', 'Finalizado')], max_length=50, verbose_name='Estado del Proyecto'),
        ),
        migrations.AlterField(
            model_name='serviciosocial',
            name='fecha_fin',
            field=models.DateField(verbose_name='Fecha de Fin'),
        ),
        migrations.AlterField(
            model_name='serviciosocial',
            name='fecha_inicio',
            field=models.DateField(verbose_name='Fecha de Inicio'),
        ),
        migrations.AlterField(
            model_name='serviciosocial',
            name='horas_cumplidas',
            field=models.PositiveIntegerField(verbose_name='Horas Cumplidas'),
        ),
        migrations.AlterField(
            model_name='serviciosocial',
            name='nombre_proyecto',
            field=models.CharField(max_length=255, verbose_name='Nombre del Proyecto'),
        ),
        migrations.AlterField(
            model_name='serviciosocial',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones Generales del Proyecto'),
        ),
        migrations.CreateModel(
            name='EstudianteServicioSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres del Estudiante')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos del Estudiante')),
                ('cedula_identidad', models.CharField(max_length=15, verbose_name='Cédula de Identidad')),
                ('seccion', models.CharField(max_length=50, verbose_name='Sección')),
                ('turno', models.CharField(choices=[('diurno', 'Diurno'), ('nocturno', 'Nocturno')], max_length=10, verbose_name='Turno')),
                ('observaciones_estudiante', models.TextField(blank=True, null=True, verbose_name='Observaciones del Estudiante')),
                ('carrera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='programacion.carrera', verbose_name='Carrera')),
                ('semestre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='programacion.semestre', verbose_name='Semestre')),
                ('servicio_social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes_participantes', to='servicio_social.serviciosocial', verbose_name='Servicio Social')),
            ],
            options={
                'verbose_name': 'Estudiante de Servicio Social',
                'verbose_name_plural': 'Estudiantes de Servicio Social',
                'unique_together': {('servicio_social', 'cedula_identidad')},
            },
        ),
    ]
