# Generated by Django 5.2 on 2025-06-15 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticaProfesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estudiante', models.CharField(max_length=255, verbose_name='Nombre del Estudiante')),
                ('cedula_estudiante', models.CharField(max_length=20, verbose_name='Cédula del Estudiante')),
                ('telefono_estudiante', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono del Estudiante')),
                ('email_estudiante', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email del Estudiante')),
                ('promedio_academico', models.DecimalField(blank=True, decimal_places=2, help_text='Ej: 8.50', max_digits=4, null=True, verbose_name='Promedio Académico (Opcional)')),
                ('nombre_empresa', models.CharField(max_length=255, verbose_name='Nombre de la Empresa/Organización')),
                ('area_departamento_empresa', models.CharField(blank=True, max_length=255, null=True, verbose_name='Área/Departamento')),
                ('nombre_tutor_externo', models.CharField(max_length=255, verbose_name='Nombre del Tutor/Supervisor Externo')),
                ('cargo_tutor_externo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo del Supervisor')),
                ('email_empresa', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email de la Empresa')),
                ('telefono_empresa', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono de la Empresa')),
                ('direccion_empresa', models.TextField(blank=True, null=True, verbose_name='Dirección Física de la Empresa')),
                ('tipo_practica', models.CharField(choices=[('obligatoria', 'Obligatoria (Pasantía)'), ('optativa', 'Optativa'), ('servicio_comunitario', 'Servicio Comunitario'), ('investigacion', 'Investigación'), ('otro', 'Otro')], default='obligatoria', max_length=50, verbose_name='Tipo de Práctica')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Finalización')),
                ('horario_practica', models.CharField(blank=True, help_text='Ej: Lunes a Viernes, 8:00 AM - 12:00 PM (20 horas/semana)', max_length=255, null=True, verbose_name='Horario (Días y Horas por semana)')),
                ('modalidad', models.CharField(choices=[('presencial', 'Presencial'), ('hibrida', 'Híbrida'), ('remota', 'Remota')], default='presencial', max_length=50, verbose_name='Modalidad')),
                ('objetivos_practica', models.TextField(blank=True, null=True, verbose_name='Objetivos de la Práctica (descripción breve)')),
                ('actividades_especificas', models.TextField(blank=True, null=True, verbose_name='Actividades Específicas a Realizar (listado o resumen)')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('finalizada', 'Finalizada')], default='pendiente', max_length=20)),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones Adicionales')),
                ('carrera_estudiante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practicas_estudiante', to='programacion.carrera', verbose_name='Carrera del Estudiante')),
                ('semestre_estudiante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practicas_estudiante', to='programacion.semestre', verbose_name='Semestre del Estudiante')),
            ],
            options={
                'verbose_name': 'Práctica Profesional',
                'verbose_name_plural': 'Prácticas Profesionales',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
