# Generated by Django 5.2 on 2025-06-04 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PracticaProfesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estudiante', models.CharField(max_length=255, verbose_name='Nombre del Estudiante')),
                ('cedula_estudiante', models.CharField(max_length=20, verbose_name='Cédula del Estudiante')),
                ('empresa', models.CharField(max_length=255)),
                ('tutor_empresa', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('finalizada', 'Finalizada')], default='pendiente', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
            ],
        ),
    ]
