# Generated by Django 5.2 on 2025-06-13 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practicas', '0001_initial'),
        ('programacion', '0015_alter_seccion_options_seccion_capacidad_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='practicaprofesional',
            options={'ordering': ['-fecha_inicio'], 'verbose_name': 'Práctica Profesional', 'verbose_name_plural': 'Prácticas Profesionales'},
        ),
        migrations.RemoveField(
            model_name='practicaprofesional',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='practicaprofesional',
            name='tutor_empresa',
        ),
        migrations.AddField(
            model_name='practicaprofesional',
            name='actividades_especificas',
            field=models.TextField(blank=True, null=True, verbose_name='Actividades Específicas a Realizar (listado o resumen)'),
        ),
        migrations.AddField(
            model_name='practicaprofesional',
            name='area_departamento_empresa',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Área/Departamento'),
        ),
        migrations.AddField(
            model_name='practicaprofesional',
            name='cargo_tutor_externo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo del Supervisor'),
        ),
        migrations.AddField(
            model_name='practicaprofesional',
            name='carrera_estudiante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practicas_estudiante', to='programacion.carrera', verbose_name='Carrera del Estudiante'),
        ),
        migrations.AddField(
            model_name='practicaprofesional',
            name='direccion_empresa',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección Física de la Empresa'),
        ),
        migrations.AddField(
            model_name='practicaprofesional',
            name='email_empresa',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email de la Empresa'),
        ),
        migrations.AddField(
            model_name='practicaprofesional',
            name='email_estudiante',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email del Estudiante'),
        ),
        migrations.AddField(
            model_name='practicaprofesional',
            name='horario_practica',
            field=models.CharField(blank=True, help_text='Ej: Lunes a Viernes, 8:00 AM - 12:00 PM (20 horas/semana)', max_length=255, null=True, verbose_name='Horario (Días y Horas por semana)'),
        ),
        migrations.AddField(
            model_name='practicaprofesional',
            name='modalidad',
            field=models.CharField(choices=[('presencial', 'Presencial'), ('hibrida', 'Híbrida'), ('remota', 'Remota')], default='presencial', max_length=50, verbose_name='Modalidad'),
        ),
        migrations.AddField(
            model_name='practicaprofesional',
            name='nombre_empresa',
            field=models.CharField(default='', max_length=255, verbose_name='Nombre de la Empresa/Organización'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='practicaprofesional',
            name='nombre_tutor_externo',
            field=models.CharField(default='', max_length=255, verbose_name='Nombre del Tutor/Supervisor Externo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='practicaprofesional',
            name='objetivos_practica',
            field=models.TextField(blank=True, null=True, verbose_name='Objetivos de la Práctica (descripción breve)'),
        ),
        migrations.AddField(
            model_name='practicaprofesional',
            name='promedio_academico',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ej: 8.50', max_digits=4, null=True, verbose_name='Promedio Académico (Opcional)'),
        ),
        migrations.AddField(
            model_name='practicaprofesional',
            name='semestre_estudiante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practicas_estudiante', to='programacion.semestre', verbose_name='Semestre del Estudiante'),
        ),
        migrations.AddField(
            model_name='practicaprofesional',
            name='telefono_empresa',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono de la Empresa'),
        ),
        migrations.AddField(
            model_name='practicaprofesional',
            name='telefono_estudiante',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono del Estudiante'),
        ),
        migrations.AddField(
            model_name='practicaprofesional',
            name='tipo_practica',
            field=models.CharField(choices=[('obligatoria', 'Obligatoria (Pasantía)'), ('optativa', 'Optativa'), ('servicio_comunitario', 'Servicio Comunitario'), ('investigacion', 'Investigación'), ('otro', 'Otro')], default='obligatoria', max_length=50, verbose_name='Tipo de Práctica'),
        ),
        migrations.AlterField(
            model_name='practicaprofesional',
            name='fecha_fin',
            field=models.DateField(verbose_name='Fecha de Finalización'),
        ),
        migrations.AlterField(
            model_name='practicaprofesional',
            name='fecha_inicio',
            field=models.DateField(verbose_name='Fecha de Inicio'),
        ),
        migrations.AlterField(
            model_name='practicaprofesional',
            name='observaciones',
            field=models.TextField(blank=True, verbose_name='Observaciones Adicionales'),
        ),
    ]
