# Generated by Django 5.2 on 2025-05-17 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=15, unique=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('entrevistado', models.BooleanField(default=False)),
                ('evaluado', models.BooleanField(default=False)),
                ('fecha_entrevista', models.DateField(blank=True, null=True)),
                ('fecha_evaluacion', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
