# Generated by Django 5.2 on 2025-05-08 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacion_academica', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programacionhoraria',
            name='aula',
        ),
        migrations.RemoveField(
            model_name='entrevistadocente',
            name='docente',
        ),
        migrations.RemoveField(
            model_name='entrevistadocente',
            name='entrevistador',
        ),
        migrations.AlterUniqueTogether(
            name='evaluaciondocente',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='evaluaciondocente',
            name='docente',
        ),
        migrations.RemoveField(
            model_name='evaluaciondocente',
            name='evaluador',
        ),
        migrations.RemoveField(
            model_name='evaluaciondocente',
            name='periodo_academico',
        ),
        migrations.RemoveField(
            model_name='evaluaciondocente',
            name='tipo_evaluacion',
        ),
        migrations.RemoveField(
            model_name='programacionhoraria',
            name='materia',
        ),
        migrations.RemoveField(
            model_name='programacionhoraria',
            name='periodo_academico',
        ),
        migrations.RemoveField(
            model_name='programacionhoraria',
            name='docente',
        ),
        migrations.AlterModelOptions(
            name='docente',
            options={},
        ),
        migrations.RemoveField(
            model_name='docente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='especialidades',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='telefono',
        ),
        migrations.AddField(
            model_name='docente',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='docente',
            name='entrevistado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='docente',
            name='evaluado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='docente',
            name='fecha_entrevista',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='docente',
            name='fecha_evaluacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='docente',
            name='cedula',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='docente',
            name='nombre_completo',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Aula',
        ),
        migrations.DeleteModel(
            name='EntrevistaDocente',
        ),
        migrations.DeleteModel(
            name='EvaluacionDocente',
        ),
        migrations.DeleteModel(
            name='TipoEvaluacion',
        ),
        migrations.DeleteModel(
            name='Materia',
        ),
        migrations.DeleteModel(
            name='PeriodoAcademico',
        ),
        migrations.DeleteModel(
            name='ProgramacionHoraria',
        ),
    ]
