# Generated by Django 5.2 on 2025-05-24 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('carrera', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('dedicacion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramacionAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fue_evaluada', models.BooleanField(default=False)),
                ('fecha_evaluacion', models.DateField(blank=True, null=True)),
                ('entrego_autoevaluacion', models.BooleanField(default=False)),
                ('evaluacion_estudiante', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('acompanamiento_docente', models.BooleanField(default=False)),
                ('autoevaluacion', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('juicio_valor', models.CharField(blank=True, max_length=100, null=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programacion.asignatura')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programacion.docente')),
                ('docente_evaluador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_realizadas', to='programacion.docente')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programacion.periodo')),
            ],
        ),
    ]
