# Generated by Django 5.2 on 2025-06-15 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10, unique=True)),
                ('tipo', models.CharField(choices=[('Teórica', 'Teórica'), ('Laboratorio', 'Laboratorio'), ('Auditorio', 'Auditorio'), ('Otro', 'Otro')], max_length=50)),
                ('capacidad', models.PositiveIntegerField()),
                ('ubicacion', models.CharField(blank=True, max_length=100)),
                ('observaciones', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre Completo')),
                ('cedula', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Cédula de Identidad')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Correo Electrónico')),
                ('dedicacion', models.CharField(max_length=50, verbose_name='Dedicación')),
                ('carreras', models.ManyToManyField(blank=True, related_name='docentes', to='programacion.carrera', verbose_name='Carreras Asignadas')),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
            },
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código de Sección')),
                ('nombre', models.CharField(blank=True, max_length=100, verbose_name='Nombre de Sección (opcional)')),
                ('turno', models.CharField(choices=[('Diurno', 'Diurno'), ('Nocturno', 'Nocturno')], default='Diurno', max_length=10, verbose_name='Turno')),
                ('capacidad', models.PositiveIntegerField(default=0, help_text='Número máximo de estudiantes', verbose_name='Capacidad')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programacion.carrera', verbose_name='Carrera')),
                ('periodo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secciones', to='programacion.periodo', verbose_name='Período Académico')),
            ],
            options={
                'verbose_name': 'Sección',
                'verbose_name_plural': 'Secciones',
            },
        ),
        migrations.CreateModel(
            name='HorarioSeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programacion.periodo')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='programacion.seccion')),
            ],
        ),
        migrations.CreateModel(
            name='semestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semestres', to='programacion.carrera')),
            ],
        ),
        migrations.AddField(
            model_name='seccion',
            name='semestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='programacion.semestre', verbose_name='Semestre'),
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(blank=True, max_length=20)),
                ('horas_teoricas', models.PositiveIntegerField(default=0)),
                ('horas_practicas', models.PositiveIntegerField(default=0)),
                ('horas_laboratorio', models.PositiveIntegerField(default=0)),
                ('diurno', models.CharField(blank=True, max_length=10)),
                ('uc', models.CharField(blank=True, max_length=10)),
                ('requisitos', models.CharField(blank=True, max_length=200)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas', to='programacion.carrera')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas', to='programacion.semestre')),
            ],
            options={
                'unique_together': {('nombre', 'carrera')},
            },
        ),
        migrations.CreateModel(
            name='ProgramacionAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fue_evaluada', models.BooleanField(default=False, verbose_name='¿Fue Evaluado por el Evaluador?')),
                ('fecha_evaluacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Evaluación')),
                ('score_acompanamiento', models.DecimalField(blank=True, decimal_places=2, help_text='Escala de 0 a 100 puntos.', max_digits=5, null=True, verbose_name='Puntaje de Acompañamiento (max 100)')),
                ('entrego_autoevaluacion', models.BooleanField(default=False, verbose_name='¿Entregó Autoevaluación?')),
                ('autoevaluacion_score', models.DecimalField(blank=True, decimal_places=2, help_text='Escala de 0 a 60 puntos.', max_digits=5, null=True, verbose_name='Puntaje de Autoevaluación (max 60)')),
                ('evaluacion_estudiante_score', models.DecimalField(blank=True, decimal_places=2, help_text='Escala de 1 a 10 puntos.', max_digits=5, null=True, verbose_name='Puntaje de Evaluación del Estudiante (max 10)')),
                ('juicio_valor', models.TextField(blank=True, help_text='Comentarios generales sobre la evaluación del docente.', null=True, verbose_name='Juicio de Valor General del Docente')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programacion.asignatura', verbose_name='Asignatura')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programacion.docente', verbose_name='Docente Evaluado')),
                ('docente_evaluador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones_realizadas', to='programacion.docente', verbose_name='Docente Evaluador')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programacion.periodo', verbose_name='Período Académico')),
            ],
            options={
                'verbose_name': 'Evaluación Docente',
                'verbose_name_plural': 'Evaluaciones Docentes',
                'unique_together': {('docente', 'asignatura', 'periodo')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='seccion',
            unique_together={('codigo', 'carrera', 'semestre', 'periodo')},
        ),
        migrations.CreateModel(
            name='HorarioAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado')], max_length=10)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('seccion', models.CharField(max_length=10)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programacion.asignatura')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programacion.aula')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programacion.carrera')),
                ('docente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='programacion.docente')),
                ('horario_seccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bloques', to='programacion.horarioseccion')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_aula', to='programacion.semestre')),
            ],
            options={
                'unique_together': {('aula', 'dia', 'hora_inicio', 'hora_fin', 'seccion')},
            },
        ),
    ]
