# Generated by Django 5.2 on 2025-05-29 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacion', '0002_alter_asignatura_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='codigo',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='diurno',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='horas_laboratorio',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='horas_practicas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='horas_teoricas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='requisitos',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='semestre',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='uc',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
