# Generated by Django 5.2 on 2025-06-16 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacion', '0003_departamento_facultad_alter_carrera_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodo',
            name='activo',
            field=models.BooleanField(default=False),
        ),
    ]
