# Generated by Django 5.2 on 2025-05-29 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacion', '0003_asignatura_codigo_asignatura_diurno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programacionacademica',
            name='docente_evaluador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_realizadas', to='programacion.docente'),
        ),
        migrations.AlterUniqueTogether(
            name='programacionacademica',
            unique_together={('docente', 'asignatura', 'periodo')},
        ),
    ]
