# Generated by Django 5.2 on 2025-05-30 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacion', '0004_alter_programacionacademica_docente_evaluador_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10, unique=True)),
                ('tipo', models.CharField(choices=[('Teórica', 'Teórica'), ('Laboratorio', 'Laboratorio'), ('Auditorio', 'Auditorio'), ('Otro', 'Otro')], max_length=50)),
                ('capacidad', models.PositiveIntegerField()),
                ('ubicacion', models.CharField(blank=True, max_length=100)),
                ('observaciones', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='HorarioAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado')], max_length=10)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('seccion', models.CharField(max_length=10)),
                ('semestre', models.CharField(blank=True, max_length=10)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programacion.asignatura')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programacion.aula')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programacion.carrera')),
            ],
            options={
                'unique_together': {('aula', 'dia', 'hora_inicio', 'hora_fin', 'seccion')},
            },
        ),
    ]
