# Generated by Django 5.2 on 2025-06-16 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacion', '0004_periodo_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='departemento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='docentes_asignados', to='programacion.departamento'),
        ),
    ]
