# Generated by Django 5.2 on 2025-06-05 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacion', '0005_aula_horarioaula'),
    ]

    operations = [
        migrations.AddField(
            model_name='horarioaula',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='programacion.docente'),
        ),
    ]
