# Generated by Django 5.2 on 2025-06-18 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacion', '0006_rename_departemento_docente_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='anios_experiencia',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Años de experiencia'),
        ),
        migrations.AddField(
            model_name='docente',
            name='areas_especializacion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Áreas de especialización'),
        ),
        migrations.AddField(
            model_name='docente',
            name='categoria_docente',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Categoría docente'),
        ),
        migrations.AddField(
            model_name='docente',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de ingreso a la institución'),
        ),
        migrations.AddField(
            model_name='docente',
            name='horario_laboral',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Horario laboral'),
        ),
        migrations.AddField(
            model_name='docente',
            name='postgrados',
            field=models.TextField(blank=True, null=True, verbose_name='Postgrados (maestrías, doctorados)'),
        ),
        migrations.AddField(
            model_name='docente',
            name='tipo_contrato',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de contrato'),
        ),
        migrations.AddField(
            model_name='docente',
            name='titulo_profesional',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Título profesional'),
        ),
    ]
