# Generated by Django 5.2 on 2025-06-24 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacion', '0007_docente_anios_experiencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='semestre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas', to='programacion.semestre'),
        ),
    ]
