# Generated by Django 5.2 on 2025-06-07 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacion', '0007_seccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioSeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programacion.periodo')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='programacion.seccion')),
            ],
        ),
    ]
