# Generated by Django 5.2 on 2025-06-08 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacion', '0008_horarioseccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='horarioaula',
            name='horario_seccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bloques', to='programacion.horarioseccion'),
        ),
    ]
