# Generated by Django 5.2 on 2025-06-25 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacion', '0008_alter_asignatura_semestre'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='horarioaula',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='docente',
            name='periodo_activo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docentes_activos', to='programacion.periodo', verbose_name='Período Activo'),
        ),
        migrations.AddField(
            model_name='horarioaula',
            name='periodo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='programacion.periodo', verbose_name='Período Académico'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='horarioaula',
            unique_together={('aula', 'dia', 'hora_inicio', 'hora_fin', 'seccion', 'periodo')},
        ),
    ]
