# Generated by Django 5.2 on 2025-06-25 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacion', '0009_alter_horarioaula_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horarioaula',
            name='periodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='programacion.periodo', verbose_name='Período Académico'),
        ),
    ]
