# Generated by Django 5.2 on 2025-06-08 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacion', '0009_horarioaula_horario_seccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='semestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semestres', to='programacion.carrera')),
            ],
        ),
    ]
