# Generated by Django 5.2 on 2025-06-10 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacion', '0010_semestre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='semestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas', to='programacion.semestre'),
        ),
        migrations.AlterField(
            model_name='horarioaula',
            name='semestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_aula', to='programacion.semestre'),
        ),
        migrations.AlterField(
            model_name='seccion',
            name='semestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='programacion.semestre'),
        ),
    ]
