# Generated by Django 5.2 on 2025-06-11 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacion', '0011_alter_asignatura_semestre_alter_horarioaula_semestre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodo',
            name='fecha_fin',
            field=models.DateField(default='2025-07-20'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='periodo',
            name='fecha_inicio',
            field=models.DateField(default='2025-03-15'),
            preserve_default=False,
        ),
    ]
