# Generated by Django 5.2 on 2025-06-11 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacion', '0012_periodo_fecha_fin_periodo_fecha_inicio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programacionacademica',
            options={'verbose_name': 'Evaluación Docente', 'verbose_name_plural': 'Evaluaciones Docentes'},
        ),
        migrations.RemoveField(
            model_name='programacionacademica',
            name='acompanamiento_docente',
        ),
        migrations.RemoveField(
            model_name='programacionacademica',
            name='autoevaluacion',
        ),
        migrations.RemoveField(
            model_name='programacionacademica',
            name='evaluacion_estudiante',
        ),
        migrations.AddField(
            model_name='programacionacademica',
            name='autoevaluacion_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Escala de 0 a 60 puntos.', max_digits=5, null=True, verbose_name='Puntaje de Autoevaluación (max 60)'),
        ),
        migrations.AddField(
            model_name='programacionacademica',
            name='evaluacion_estudiante_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Escala de 1 a 10 puntos.', max_digits=5, null=True, verbose_name='Puntaje de Evaluación del Estudiante (max 10)'),
        ),
        migrations.AddField(
            model_name='programacionacademica',
            name='score_acompanamiento',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Escala de 0 a 100 puntos.', max_digits=5, null=True, verbose_name='Puntaje de Acompañamiento (max 100)'),
        ),
        migrations.AlterField(
            model_name='programacionacademica',
            name='asignatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programacion.asignatura', verbose_name='Asignatura'),
        ),
        migrations.AlterField(
            model_name='programacionacademica',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programacion.docente', verbose_name='Docente Evaluado'),
        ),
        migrations.AlterField(
            model_name='programacionacademica',
            name='docente_evaluador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluaciones_realizadas', to='programacion.docente', verbose_name='Docente Evaluador'),
        ),
        migrations.AlterField(
            model_name='programacionacademica',
            name='entrego_autoevaluacion',
            field=models.BooleanField(default=False, verbose_name='¿Entregó Autoevaluación?'),
        ),
        migrations.AlterField(
            model_name='programacionacademica',
            name='fecha_evaluacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Evaluación'),
        ),
        migrations.AlterField(
            model_name='programacionacademica',
            name='fue_evaluada',
            field=models.BooleanField(default=False, verbose_name='¿Fue Evaluado por el Evaluador?'),
        ),
        migrations.AlterField(
            model_name='programacionacademica',
            name='juicio_valor',
            field=models.TextField(blank=True, help_text='Comentarios generales sobre la evaluación del docente.', null=True, verbose_name='Juicio de Valor General del Docente'),
        ),
        migrations.AlterField(
            model_name='programacionacademica',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programacion.periodo', verbose_name='Período Académico'),
        ),
    ]
