# Generated by Django 5.2 on 2025-06-11 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacion', '0013_alter_programacionacademica_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='docente',
            options={'verbose_name': 'Docente', 'verbose_name_plural': 'Docentes'},
        ),
        migrations.AddField(
            model_name='docente',
            name='cedula',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Cédula de Identidad'),
        ),
        migrations.AddField(
            model_name='docente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AddField(
            model_name='docente',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de Teléfono'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='carreras',
            field=models.ManyToManyField(blank=True, related_name='docentes', to='programacion.carrera', verbose_name='Carreras Asignadas'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='dedicacion',
            field=models.CharField(max_length=50, verbose_name='Dedicación'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre Completo'),
        ),
    ]
