# Generated by Django 5.2 on 2025-06-13 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacion', '0014_alter_docente_options_docente_cedula_docente_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seccion',
            options={'verbose_name': 'Sección', 'verbose_name_plural': 'Secciones'},
        ),
        migrations.AddField(
            model_name='seccion',
            name='capacidad',
            field=models.PositiveIntegerField(default=0, help_text='Número máximo de estudiantes', verbose_name='Capacidad'),
        ),
        migrations.AddField(
            model_name='seccion',
            name='periodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secciones', to='programacion.periodo', verbose_name='Período Académico'),
        ),
        migrations.AddField(
            model_name='seccion',
            name='turno',
            field=models.CharField(choices=[('Diurno', 'Diurno'), ('Nocturno', 'Nocturno')], default='Diurno', max_length=10, verbose_name='Turno'),
        ),
        migrations.AlterField(
            model_name='seccion',
            name='carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programacion.carrera', verbose_name='Carrera'),
        ),
        migrations.AlterField(
            model_name='seccion',
            name='codigo',
            field=models.CharField(max_length=20, unique=True, verbose_name='Código de Sección'),
        ),
        migrations.AlterField(
            model_name='seccion',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre de Sección (opcional)'),
        ),
        migrations.AlterField(
            model_name='seccion',
            name='semestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='programacion.semestre', verbose_name='Semestre'),
        ),
        migrations.AlterUniqueTogether(
            name='seccion',
            unique_together={('codigo', 'carrera', 'semestre', 'periodo')},
        ),
    ]
